// /lib/fabric-converter.ts
// Converts Satori's calculated layout into Fabric.js-compatible JSON
// so the existing Lovable editor can display and edit the design

import { SatoriNode, MoodName, DecorationType } from './types.js';
import { DerivedPalette, derivePalette, hexToRgb } from './contrast.js';

// ── Fabric.js Output Types ───────────────────────────────────

export interface FabricBackground {
  type: 'solid' | 'gradient';
  color?: string;
  gradientType?: 'linear';
  coords?: { x1: number; y1: number; x2: number; y2: number };
  colorStops?: { offset: number; color: string }[];
}

export interface FabricElement {
  type: 'textbox' | 'rect' | 'circle' | 'line';
  id?: string;
  left: number;
  top: number;
  width?: number;
  height?: number;
  text?: string;
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: number;
  fontStyle?: string;
  fill?: string;
  opacity?: number;
  textAlign?: string;
  lineHeight?: number;
  // Rect/Circle specific
  radius?: number;
  rx?: number;
  ry?: number;
  stroke?: string;
  strokeWidth?: number;
  // Shadow
  shadow?: { color: string; blur: number; offsetX: number; offsetY: number };
  // Metadata
  editable?: boolean;
  role?: string; // 'title' | 'subtitle' | 'body' | 'accent' | 'brand' | 'counter' | 'cta' | 'decoration'
}

export interface FabricSlide {
  slide_number: number;
  slide_type: string;
  background: FabricBackground;
  elements: FabricElement[];
}

export interface FabricCarouselData {
  total_slides: number;
  dimensions: { width: number; height: number };
  mood: string;
  decoration: string;
  slides: FabricSlide[];
}

export interface FabricSingleData {
  dimensions: { width: number; height: number };
  mood: string;
  background: FabricBackground;
  elements: FabricElement[];
}

// ── SVG Parser ───────────────────────────────────────────────
// Extracts text positions from SVG generated by Satori

interface ExtractedTextElement {
  text: string;
  x: number;
  y: number;
  fontSize: number;
  fontFamily: string;
  fontWeight: string;
  fill: string;
  opacity: number;
}

function extractTextsFromSVG(svg: string): ExtractedTextElement[] {
  const texts: ExtractedTextElement[] = [];
  
  // Match all <text> elements in the SVG
  // Satori outputs text as: <text x="..." y="..." font-size="..." font-family="..." fill="...">content</text>
  const textRegex = /<text[^>]*>([\s\S]*?)<\/text>/gi;
  let match;
  
  while ((match = textRegex.exec(svg)) !== null) {
    const tag = match[0];
    const innerContent = match[1];
    
    // Extract attributes
    const x = parseFloat(extractAttr(tag, 'x') || '0');
    const y = parseFloat(extractAttr(tag, 'y') || '0');
    const fontSize = parseFloat(extractAttr(tag, 'font-size') || '16');
    const fontFamily = extractAttr(tag, 'font-family') || 'Inter';
    const fontWeight = extractAttr(tag, 'font-weight') || '400';
    const fill = extractAttr(tag, 'fill') || '#000000';
    const opacity = parseFloat(extractAttr(tag, 'opacity') || '1');
    
    // Clean text content (remove nested tags)
    const cleanText = innerContent
      .replace(/<[^>]+>/g, '')
      .replace(/&#x27;/g, "'")
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .trim();
    
    if (cleanText) {
      texts.push({ text: cleanText, x, y, fontSize, fontFamily, fontWeight, fill, opacity });
    }
  }
  
  return texts;
}

function extractAttr(tag: string, attr: string): string | null {
  // Handle both regular attributes and style properties
  // Satori sometimes puts things in style="..." and sometimes as direct attributes
  
  // Try direct attribute first
  const directRegex = new RegExp(`${attr}="([^"]*)"`, 'i');
  const directMatch = tag.match(directRegex);
  if (directMatch) return directMatch[1];
  
  // Try in style attribute (font-size → fontSize mapping)
  const styleMatch = tag.match(/style="([^"]*)"/);
  if (styleMatch) {
    const style = styleMatch[1];
    // CSS property name (with hyphens)
    const cssRegex = new RegExp(`${attr}\\s*:\\s*([^;]+)`, 'i');
    const cssMatch = style.match(cssRegex);
    if (cssMatch) return cssMatch[1].trim();
  }
  
  return null;
}

// ── Extract rect/circle decorations from SVG ─────────────────

interface ExtractedRect {
  x: number;
  y: number;
  width: number;
  height: number;
  fill: string;
  opacity: number;
  rx: number;
}

function extractRectsFromSVG(svg: string): ExtractedRect[] {
  const rects: ExtractedRect[] = [];
  const rectRegex = /<rect[^>]*\/?>|<rect[^>]*>[\s\S]*?<\/rect>/gi;
  let match;
  
  while ((match = rectRegex.exec(svg)) !== null) {
    const tag = match[0];
    const x = parseFloat(extractAttr(tag, 'x') || '0');
    const y = parseFloat(extractAttr(tag, 'y') || '0');
    const width = parseFloat(extractAttr(tag, 'width') || '0');
    const height = parseFloat(extractAttr(tag, 'height') || '0');
    const fill = extractAttr(tag, 'fill') || 'transparent';
    const opacity = parseFloat(extractAttr(tag, 'opacity') || '1');
    const rx = parseFloat(extractAttr(tag, 'rx') || '0');
    
    // Skip the main canvas rect
    if (width > 1000 && height > 1000) continue;
    
    rects.push({ x, y, width, height, fill, opacity, rx });
  }
  
  return rects;
}

// ── Background Builder ───────────────────────────────────────

function buildFabricBackground(
  mood: MoodName,
  palette: DerivedPalette,
  width: number,
  height: number
): FabricBackground {
  switch (mood) {
    case 'warm_gradient':
      return {
        type: 'gradient',
        gradientType: 'linear',
        coords: { x1: 0, y1: 0, x2: width, y2: height },
        colorStops: [
          { offset: 0, color: palette.gradientFrom },
          { offset: 1, color: palette.gradientTo },
        ],
      };

    case 'dark_minimal':
    case 'bold_primary':
      return { type: 'solid', color: palette.bgMain };

    case 'light_clean':
      return { type: 'solid', color: palette.bgMain };

    case 'soft_pastel':
      return {
        type: 'gradient',
        gradientType: 'linear',
        coords: { x1: 0, y1: 0, x2: width, y2: height },
        colorStops: [
          { offset: 0, color: palette.gradientFrom },
          { offset: 1, color: palette.gradientTo },
        ],
      };

    case 'color_block':
      // Color block uses split panel — solid white for the main area
      return { type: 'solid', color: palette.bgMain };

    default:
      return { type: 'solid', color: palette.bgMain };
  }
}

// ── Match SVG texts to semantic roles ────────────────────────
// Uses position heuristics to identify which text is title, body, etc.

function assignRoles(
  texts: ExtractedTextElement[],
  width: number,
  height: number
): (ExtractedTextElement & { role: string })[] {
  if (texts.length === 0) return [];

  // Sort by Y position (top to bottom)
  const sorted = [...texts].sort((a, b) => a.y - b.y);
  
  // Find the largest font size — that's likely the title or stat
  const maxFontSize = Math.max(...sorted.map(t => t.fontSize));
  
  return sorted.map((t, i) => {
    let role = 'body';
    
    // Very large text = stat number
    if (t.fontSize >= maxFontSize * 0.9 && t.fontSize > 80) {
      role = 'stat';
    }
    // Largest text = title
    else if (t.fontSize >= maxFontSize * 0.85) {
      role = 'title';
    }
    // Small text at top = subtitle/category
    else if (t.y < height * 0.2 && t.fontSize < maxFontSize * 0.5) {
      role = 'subtitle';
    }
    // Small text at bottom = brand or counter
    else if (t.y > height * 0.85) {
      if (t.x < width * 0.3) role = 'brand';
      else role = 'counter';
    }
    // Text near CTA position
    else if (t.text === 'Desliza →' || t.text.includes('Desliza') || t.text === 'Saber más') {
      role = 'cta';
    }
    // Quote mark
    else if (t.text === '\u201C' || t.text === '"') {
      role = 'decoration';
    }
    // Attribution (starts with —)
    else if (t.text.startsWith('—') || t.text.startsWith('-')) {
      role = 'attribution';
    }
    // Medium size after title = body
    else {
      role = 'body';
    }
    
    return { ...t, role };
  });
}

// ── Main Conversion Function ─────────────────────────────────

export function svgToFabricElements(
  svg: string,
  width: number,
  height: number,
  mood: MoodName,
  palette: DerivedPalette
): { background: FabricBackground; elements: FabricElement[] } {
  
  const background = buildFabricBackground(mood, palette, width, height);
  const elements: FabricElement[] = [];
  
  // Extract and convert text elements
  const rawTexts = extractTextsFromSVG(svg);
  const roledTexts = assignRoles(rawTexts, width, height);
  
  for (const t of roledTexts) {
    // Skip decoration elements (quote marks rendered as text)
    if (t.role === 'decoration' && t.text.length <= 2) continue;
    
    // Estimate text width based on content length and font size
    const estimatedWidth = Math.min(
      width * 0.85,
      Math.max(t.text.length * t.fontSize * 0.55, width * 0.4)
    );
    
    elements.push({
      type: 'textbox',
      id: `${t.role}_${elements.length}`,
      left: Math.round(t.x),
      top: Math.round(t.y - t.fontSize), // SVG y is baseline, Fabric y is top
      width: Math.round(estimatedWidth),
      text: t.text,
      fontSize: Math.round(t.fontSize),
      fontFamily: t.fontFamily.replace(/"/g, ''),
      fontWeight: parseInt(t.fontWeight) || 400,
      fill: t.fill,
      opacity: t.opacity,
      textAlign: t.role === 'title' || t.role === 'stat' || t.role === 'body' ? 'center' : 'left',
      lineHeight: t.role === 'body' ? 1.6 : 1.2,
      editable: !['brand', 'counter', 'decoration', 'cta'].includes(t.role),
      role: t.role,
    });
  }
  
  // Extract decoration rects (accent lines, geometric shapes)
  const rects = extractRectsFromSVG(svg);
  for (const r of rects) {
    // Skip very small rects (likely artifacts)
    if (r.width < 3 && r.height < 3) continue;
    
    // Thin horizontal/vertical lines = accent decorations
    if (r.width <= 5 || r.height <= 5) {
      elements.push({
        type: 'rect',
        id: `accent_${elements.length}`,
        left: Math.round(r.x),
        top: Math.round(r.y),
        width: Math.round(r.width),
        height: Math.round(r.height),
        fill: r.fill,
        opacity: r.opacity,
        rx: Math.round(r.rx),
        ry: Math.round(r.rx),
        editable: false,
        role: 'accent',
      });
    }
    // Larger rects with low opacity = decoration blocks
    else if (r.opacity < 0.3) {
      elements.push({
        type: 'rect',
        id: `deco_${elements.length}`,
        left: Math.round(r.x),
        top: Math.round(r.y),
        width: Math.round(r.width),
        height: Math.round(r.height),
        fill: r.fill,
        opacity: r.opacity,
        rx: Math.round(r.rx),
        ry: Math.round(r.rx),
        editable: false,
        role: 'decoration',
      });
    }
    // Color panel (for split_panel layout)
    else if (r.width > width * 0.2 && r.height > height * 0.5) {
      elements.push({
        type: 'rect',
        id: `panel_${elements.length}`,
        left: Math.round(r.x),
        top: Math.round(r.y),
        width: Math.round(r.width),
        height: Math.round(r.height),
        fill: r.fill,
        opacity: r.opacity,
        editable: false,
        role: 'panel',
      });
    }
  }
  
  // Extract circles (geometric_circles decoration)
  const circleRegex = /<circle[^>]*\/?>|<ellipse[^>]*\/?>/gi;
  let circleMatch;
  while ((circleMatch = circleRegex.exec(svg)) !== null) {
    const tag = circleMatch[0];
    const cx = parseFloat(extractAttr(tag, 'cx') || extractAttr(tag, 'x') || '0');
    const cy = parseFloat(extractAttr(tag, 'cy') || extractAttr(tag, 'y') || '0');
    const r = parseFloat(extractAttr(tag, 'r') || extractAttr(tag, 'rx') || '0');
    const fill = extractAttr(tag, 'fill') || 'transparent';
    const opacity = parseFloat(extractAttr(tag, 'opacity') || '1');
    
    if (r > 5) {
      elements.push({
        type: 'circle',
        id: `circle_${elements.length}`,
        left: Math.round(cx - r),
        top: Math.round(cy - r),
        radius: Math.round(r),
        fill,
        opacity,
        editable: false,
        role: 'decoration',
      });
    }
  }
  
  return { background, elements };
}

// ── High-level: Convert a full slide ─────────────────────────

export function convertSlideToFabric(
  svg: string,
  slideData: {
    slide_number: number;
    slide_type: string;
    mood: MoodName;
    width: number;
    height: number;
    primary: string;
    secondary: string;
  }
): FabricSlide {
  const paletteType = ({
    dark_minimal: 'dark',
    light_clean: 'light',
    bold_primary: 'bold',
    soft_pastel: 'pastel',
    color_block: 'split',
    warm_gradient: 'gradient',
  } as const)[slideData.mood];
  
  const palette = derivePalette(slideData.primary, slideData.secondary, paletteType);
  const { background, elements } = svgToFabricElements(
    svg, slideData.width, slideData.height, slideData.mood, palette
  );
  
  return {
    slide_number: slideData.slide_number,
    slide_type: slideData.slide_type,
    background,
    elements,
  };
}
